# Generated by Django 3.0.6 on 2020-06-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='currentdate',
            new_name='current_date',
        ),
    ]
