# Generated by Django 3.0.6 on 2020-06-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0005_auto_20200614_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='home_type',
            field=models.CharField(choices=[('Single Family', 'Single Family'), ('Duplex', 'Duplex'), ('Multi-Family', 'Multi-Family'), ('Townhome', 'Townhome'), ('Manufactured Home', 'Manufactured Home')], default='Single Family', max_length=30, null=True),
        ),
    ]
