# Generated by Django 3.0.6 on 2020-06-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0006_home_home_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='year_built',
            field=models.PositiveIntegerField(default=2020),
        ),
    ]
