# Generated by Django 3.0.6 on 2020-06-14 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0007_home_year_built'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='year_built',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
