# Generated by Django 3.0.6 on 2020-06-14 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0008_auto_20200614_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(750000000)]),
        ),
    ]
