# Generated by Django 3.0.6 on 2020-06-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0009_auto_20200614_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='cooling_system',
            field=models.CharField(choices=[('Central', 'Central'), ('Ductless', 'Ductless'), ('Heat Pump', 'Heat Pump'), ('Evaoporative', 'Evaporative')], default='Central', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='heating_system1',
            field=models.CharField(choices=[('Forced Air (gas)', 'Forced Air (gas)'), ('Electric', 'Electric'), ('Geothermal', 'Geothermal'), ('Radiant Heat', 'Radiant Heat'), ('Steam Radiant Heat', 'Steam Radiant Heat')], default='Electric', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='heating_system2',
            field=models.CharField(choices=[('Forced Air (gas)', 'Forced Air (gas)'), ('Electric', 'Electric'), ('Geothermal', 'Geothermal'), ('Radiant Heat', 'Radiant Heat'), ('Steam Radiant Heat', 'Steam Radiant Heat')], default=None, max_length=50, null=True),
        ),
    ]
