# Generated by Django 3.0.6 on 2020-06-16 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0017_auto_20200615_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='HOA_info',
            field=models.CharField(default='No HOA', max_length=200),
        ),
        migrations.AddField(
            model_name='home',
            name='green_energy',
            field=models.TextField(default='No green energy utilities'),
        ),
        migrations.AddField(
            model_name='home',
            name='listing_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='major_remodel_year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2020)]),
        ),
        migrations.AddField(
            model_name='home',
            name='mls_status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='home',
            name='sewer_info',
            field=models.CharField(choices=[('public sewer', 'public sewer'), ('septic system', 'septic system')], default='public sewer', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='utilities',
            field=models.TextField(null=True),
        ),
    ]
