# Generated by Django 3.0.6 on 2020-06-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0018_auto_20200616_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='mls_status',
            field=models.CharField(default='active', max_length=30),
        ),
    ]
