# Generated by Django 3.0.6 on 2020-06-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0019_auto_20200616_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='mls_status',
            field=models.CharField(choices=[('coming soon', 'coming soon'), ('active', 'active'), ('contingent', 'contingent'), ('pending', 'pending'), ('closed', 'closed'), ('expired', 'expired'), ('canceled', 'canceled'), ('withdrawn', 'withdrawn')], default='active', max_length=30),
        ),
    ]
