# Generated by Django 3.0.6 on 2020-06-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0021_auto_20200616_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='parking_spcaes',
            new_name='parking_spcaces',
        ),
    ]
