# Generated by Django 3.0.6 on 2020-06-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0022_auto_20200616_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='parking_spcaces',
            new_name='parking_spaces',
        ),
    ]
