# Generated by Django 3.0.6 on 2020-06-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0023_auto_20200616_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='master_bedrooom',
            new_name='master_bedroom',
        ),
    ]
