# Generated by Django 3.0.6 on 2020-06-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0024_auto_20200616_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='master_bathroom',
            field=models.BooleanField(default=True),
        ),
    ]
