# Generated by Django 3.0.6 on 2020-06-17 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0028_auto_20200617_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='major_remodel_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2020)]),
        ),
        migrations.AlterField(
            model_name='home',
            name='master_bathroom',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='Yes', max_length=10, verbose_name='Master Bath?'),
        ),
    ]
