# Generated by Django 3.0.6 on 2020-06-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0029_auto_20200617_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='appliances',
            field=models.TextField(null=True),
        ),
    ]
