# Generated by Django 3.0.6 on 2020-06-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0030_home_appliances'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='other_interior_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='appliances',
            field=models.TextField(blank=True, default='NA', null=True),
        ),
    ]
