# Generated by Django 3.0.6 on 2020-06-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0031_auto_20200617_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='attached_garage',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='home',
            name='master_bathroom',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10, verbose_name='Master Bath?'),
        ),
        migrations.AlterField(
            model_name='home',
            name='master_bedroom',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10, verbose_name='Master Bedroom?'),
        ),
        migrations.AlterField(
            model_name='home',
            name='new_construction',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
