# Generated by Django 3.0.6 on 2020-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0032_auto_20200617_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='parcel_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='zoning',
            field=models.CharField(blank=True, default='NA', max_length=10, null=True),
        ),
    ]
