# Generated by Django 3.0.6 on 2020-06-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0033_auto_20200617_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='year_built',
            field=models.PositiveIntegerField(default=2020),
        ),
    ]
