# Generated by Django 3.0.6 on 2020-06-22 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0034_auto_20200622_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='full_bathrooms',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='half_bathrooms',
            field=models.PositiveIntegerField(null=True, verbose_name='1/2 Bathroom'),
        ),
        migrations.AlterField(
            model_name='home',
            name='one_quarter_bathrooms',
            field=models.PositiveIntegerField(null=True, verbose_name='1/4 Bathroom'),
        ),
        migrations.AlterField(
            model_name='home',
            name='three_quarter_bathrooms',
            field=models.PositiveIntegerField(null=True, verbose_name='3/4 Bathroom'),
        ),
        migrations.AlterField(
            model_name='home',
            name='year_built',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
