# Generated by Django 3.0.6 on 2020-06-13 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='client',
        ),
        migrations.RemoveField(
            model_name='financial',
            name='credit',
        ),
        migrations.AddField(
            model_name='client',
            name='credit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Credit'),
        ),
    ]
